# Generated by Django 5.0.1 on 2024-01-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbcat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebook',
            name='slug',
            field=models.SlugField(default='#', max_length=255),
        ),
    ]
