# Generated by Django 5.0.1 on 2024-01-13 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbcat', '0004_category_facebook_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebook',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fbcat.category'),
        ),
    ]
