# Generated by Django 5.0.1 on 2024-01-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbcat', '0005_alter_facebook_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='facebook',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='fbcat.tagpost'),
        ),
    ]
