# Generated by Django 5.0.1 on 2024-01-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbcat', '0006_tagpost_facebook_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebook',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'DRAFT'), (1, 'PUBLISHED')], default=1),
        ),
    ]
